(function(w){
  'use strict';
  const A=()=>w.Aurora2;
  const num=id=>{const el=document.getElementById(id);const n=Number(el?.value);return Number.isFinite(n)?Math.max(0,n):0};
  const val=id=>document.getElementById(id)?.value||'';
  const setVal=(id,v)=>{const el=document.getElementById(id);if(el)el.value=v??''};
  function calc(plan){
    const totalCash=plan.openingCash+plan.netPay+plan.extraCash;
    const commitments=plan.billsDue+plan.potsDue+plan.otherPlanned;
    const safeSurplus=Math.max(0,totalCash-commitments-plan.protectedCash);
    return {totalCash,commitments,safeSurplus};
  }
  function readForm(){return {paydayDate:val('paydayDate'),openingCash:num('openingCash'),netPay:num('netPay'),extraCash:num('extraCash'),billsDue:num('billsDue'),potsDue:num('potsDue'),otherPlanned:num('otherPlanned'),protectedCash:num('protectedCash'),releaseAmount:num('releaseAmount')}}
  function savePlan(){const plan=readForm();const c=calc(plan);A().core.update(s=>({...s,finance:{...s.finance,plan,lastCalculatedAt:new Date().toISOString()}}));renderPlan(plan,c);return {plan,c};}
  function renderPlan(plan,c){const ui=A().ui;ui.text('mOpening',ui.money(plan.openingCash));ui.text('mPay',ui.money(plan.netPay));ui.text('mCommitments',ui.money(c.commitments));ui.text('mProtected',ui.money(plan.protectedCash));ui.text('mAvailable',ui.money(c.safeSurplus));ui.text('breakTotal',ui.money(c.totalCash));ui.text('breakBills',`− ${ui.money(plan.billsDue)}`);ui.text('breakPots',`− ${ui.money(plan.potsDue)}`);ui.text('breakOther',`− ${ui.money(plan.otherPlanned)}`);ui.text('breakProtected',`− ${ui.money(plan.protectedCash)}`);ui.text('breakAvailable',ui.money(c.safeSurplus));const release=document.getElementById('releaseAmount');if(release&&document.activeElement!==release&&(!release.value||Number(release.value)>c.safeSurplus))release.value=c.safeSurplus?c.safeSurplus.toFixed(2):'';renderReleaseGuard(c.safeSurplus);}
  function renderReleaseGuard(safe){const requested=num('releaseAmount');const msg=document.getElementById('releaseGuard');const btn=document.getElementById('releaseMission');if(!msg||!btn)return;if(requested<=0){msg.className='notice';msg.textContent='Enter the amount you want Finance to release to Transfer. It can be lower than the safe surplus.';btn.disabled=true;return;}if(requested>safe+0.005){msg.className='notice red';msg.textContent=`Blocked: requested release is above the calculated safe surplus of ${A().ui.money(safe)}.`;btn.disabled=true;return;}msg.className='notice good';msg.textContent=`Finance can release ${A().ui.money(requested)}. Transfer will receive this exact locked budget.`;btn.disabled=false;}
  function releaseMission(){const {plan,c}=savePlan();const amount=num('releaseAmount');if(amount<=0||amount>c.safeSurplus+0.005)return;const current=A().core.read();if(current.mission&&current.mission.status&&!['FINANCE_APPROVED','CANCELLED'].includes(current.mission.status)){alert('This mission has already moved beyond Finance and is locked. Finish or cancel it in the owning department before replacing it.');return;}const mission={id:current.mission?.status==='FINANCE_APPROVED'?current.mission.id:A().core.uid('MISSION'),approvedBudget:Number(amount.toFixed(2)),status:'FINANCE_APPROVED',paydayDate:plan.paydayDate||'',createdAt:current.mission?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),source:'Finance',financeSnapshot:{totalCash:Number(c.totalCash.toFixed(2)),commitments:Number(c.commitments.toFixed(2)),protectedCash:Number(plan.protectedCash.toFixed(2)),safeSurplus:Number(c.safeSurplus.toFixed(2))}};A().core.update(s=>({...s,finance:{...s.finance,plan:{...plan,releaseAmount:amount},lastReleasedAt:new Date().toISOString()},mission,alerts:[{id:A().core.uid('ALERT'),title:`Finance released ${A().ui.money(amount)}`,note:'Investment mission is ready for Scouting and Transfer.',when:'now'},...(s.alerts||[]).filter(x=>!String(x?.title||'').startsWith('Finance released '))].slice(0,8)}));renderMission();showToast('Investment mission released to Aurora 2.0.');}
  function renderMission(){const s=A().core.read(),m=s.mission,ui=A().ui;ui.text('missionStatus',m?.status==='FINANCE_APPROVED'?'FINANCE APPROVED':m?.status||'NO ACTIVE MISSION');ui.text('missionAmount',m?.approvedBudget!=null?ui.money(m.approvedBudget):'£0.00');ui.text('missionMeta',m?`${m.id}${m.paydayDate?' • payday '+m.paydayDate:''}`:'Nothing has been released to Transfer yet.');const lock=document.getElementById('missionLock');if(lock)lock.textContent=m?.status==='FINANCE_APPROVED'?'Budget locked at Finance. Transfer may read it but cannot overwrite it.':'Finance owns the investment budget.';}
  function load(){const s=A().core.read(),p=s.finance?.plan||{};['paydayDate','openingCash','netPay','extraCash','billsDue','potsDue','otherPlanned','protectedCash','releaseAmount'].forEach(id=>setVal(id,p[id]??''));renderPlan(p,calc(p));renderMission();A().ui.text('lastUpdated',new Date(s.updatedAt).toLocaleString('en-GB'));}
  function wire(){document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===btn.dataset.tab));}));document.querySelectorAll('#paydayPanel input').forEach(el=>el.addEventListener('input',()=>{const plan=readForm(),c=calc(plan);renderPlan(plan,c);renderReleaseGuard(c.safeSurplus);}));document.getElementById('savePlan')?.addEventListener('click',()=>{savePlan();showToast('Payday plan saved locally in Aurora 2.0.');});document.getElementById('releaseMission')?.addEventListener('click',releaseMission);}
  function showToast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.style.opacity='1';clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.style.opacity='0',2800);}
  document.addEventListener('DOMContentLoaded',()=>{load();wire();});w.addEventListener('aurora2:state',()=>{renderMission();A().ui.text('lastUpdated',new Date(A().core.read().updatedAt).toLocaleString('en-GB'));});
})(window);
